name: Deploy to GitHub Pages after success test

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for index.html
        id: check_file
        run: |
          if [ -f "index.html" ]; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Pages
        if: steps.check_file.outputs.found == 'true'
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: steps.check_file.outputs.found == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        if: steps.check_file.outputs.found == 'true'
        uses: actions/deploy-pages@v4
